osx_image: xcode8.3
language: objective-c
install:
  - bundle install --path vendor/bundle
  - bundle exec pod install
  - bundle exec keys set TumblrOAuthConsumerKey $TUMBLR_OAUTH_CONSUMER_KEY
  - bundle exec keys set TumblrOAuthConsumerSecret $TUMBLR_OAUTH_CONSUMER_SECRET
